services:
  - type: web
    name: rds-group-client
    env: node
    workingDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromSecret: vite_api_url
    staticPublishPath: dist

  - type: web
    name: rds-group-server
    env: node
    workingDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: mongodb_uri
      - key: PORT
        value: 10000
