services:
  - type: web
    name: rds-group-client
    env: node
    buildCommand: npm run build
    startCommand: npm run start:client
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromSecret: vite_api_url
    staticPublishPath: client/dist

  - type: web
    name: rds-group-server
    env: node
    buildCommand: npm run install:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: mongodb_uri
      - key: PORT
        value: 10000
